services:
    lmsbooks:
        image: lmsbooks:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8087:8080"
        environment:
            SPRING_PROFILES_ACTIVE: bootstrap, relational, IDService1
        networks:
            - lms_network2
        volumes:
            - "uploaded_files_volume_1:/tmp"
        deploy:
            mode: replicated
            replicas: 2

networks:
    lms_network2:
        external: true

volumes:
    uploaded_files_volume_1:
    uploaded_files_volume_2:
